---
baseURL: https://phillycommunitywireless.org
languageCode: en-us
defaultContentLanguage: en
title: Philly Community Wireless
author: Philly Community Wireless
theme: pcw-hugo-theme
enableRobotsTXT: true
languages:
  en:
    languageName: English
    contentDir: content/en
    menu:
      main:
        - name: Connect
          url: "/getconnected"
          weight: "1"
        - name: Volunteer
          url: "/volunteer"
          weight: "2"
        - name: Map
          url: "/networkmap"
          weight: "3"
        - name: About
          url: "/about"
          weight: "4"
        - name: People
          url: "/people"
          weight: "5"
        - name: Partners
          url: "/partners"
          weight: "6"
        - name: FAQ
          url: "/faq"
          weight: "7"
        - name: Donate
          url: https://phillycommunitywireless.allyrafundraising.com/
          params:
            external: true
          weight: "8"
        - name: Docs
          url: https://docs.phillycommunitywireless.org/en/latest/
          params:
            external: true
          weight: "9"
      footer:
        - name: Code of Conduct
          url: "/code-of-conduct"
          weight: "1"
        - name: Terms of Service
          url: "/termsofservice"
          weight: "2"
    weight: "1"
    params:
      featured_text:
        subtitle: Building community-controlled networks in Philadelphia
        link: Learn more &rarr;
  es:
    languageName: Español
    contentDir: content/es
    menu:
      main:
        - name: Conéctate
          url: "/getconnected"
          weight: "1"
        - name: Voluntario
          url: "/volunteer"
          weight: "2"
        - name: Navegacion
          url: "/networkmap"
          weight: "3"
        - name: Acerca
          url: "/about"
          weight: "4"
        - name: Equipo
          url: "/people"
          weight: "5"
        - name: Partners
          url: "/partners"
          weight: "6"
        - name: FAQ
          url: "/faq"
          weight: "7"
        - name: Donate
          url: https://phillycommunitywireless.allyrafundraising.com/
          params:
            external: true
          weight: "8"
        - name: Docs
          url: https://docs.phillycommunitywireless.org/es/latest/
          params:
            external: true
          weight: "9"
      footer:
        - name: Código de conducta
          url: "/code-of-conduct"
          weight: "1"
    weight: "2"
    params:
      featured_text:
        subtitle: Construyendo redes controladas por la comunidad en Filadelfia
        link: Aprende más &rarr;
params:
  site_logo: "/images/WebLogo_Standard2.svg"
  site_logo_inverted: "/images/WebLogo_Inverted2.svg"
  attribution:
    name: Addie Barron
    link: https://addieis.online
  featured_image:
    src: "/images/hero3.jpg"
    alt:
      A photo of an antenna installed on a rooftop, pointing at a receiver tower
      in the distance.
  featured_text:
    header: "/images/WebLogo_Standard.svg"
  background_color_class: bg-near-white black-60
  body_classes: calibre black
  custom_css:
    - colors.css
    - custom.css
    - focus-indicators.css
    - fonts.css
markup:
  tableOfContents:
    startLevel: 0
  goldmark:
    renderer:
      unsafe: true
