---
baseURL: https://phillycommunitywireless.org
languageCode: en-us
defaultContentLanguage: en
title: Philly Community Wireless
author: Philly Community Wireless
theme: pcw-hugo-theme
enableRobotsTXT: true
languages:
  en:
    languageName: English
    contentDir: content/en
    menu:
      main:
        # Programs
        - name: Programs
          identifier: Programs
          weight: "1"
        - name: Get Connected
          url: "/getconnected"
          parent: Programs
          weight: "1"
        - name: Volunteer
          url: "/volunteer"
          parent: Programs
          weight: "2"        

        # Support
        - name: Support
          identifier: support
          weight: "2"
        - name: Donate
          url: "https://phillycommunitywireless.allyrafundraising.com/"
          params:
            external: true
          parent: support
          weight: "3"
        - name: Merch
          url: "/merch"
          parent: support
          weight: "2"
        - name: Support Us
          url: "/support"
          parent: support
          weight: "1"

        # About
        - name: About 
          identifier: about-us
          weight: "3"
        - name: About Us
          url: "/about"
          parent: about-us
          weight: "1"
        - name: People
          url: "/about/people"
          parent: about-us
          weight: "2"
        - name: Partners
          url: "/about/partners"
          parent: about-us
          weight: "3"
        - name: Funders
          url: "/about/funders"
          parent: about-us
          weight: "4"
        - name: In the News 
          url: "/about/news"
          parent: about-us
          weight: "5"
        - name: FAQ
          url: "/about/faq"
          parent: about-us
          weight: "6"
     

        - name: Location
          url: "/networklocation"
          weight: "4"

        - name: Docs
          url: https://docs.phillycommunitywireless.org/en/latest/
          params:
            external: true
          weight: "9"
    weight: "1"
    params:
      featured_text:
        header: "/images/WebLogo_Standard.svg"
        subtitle: Building community-controlled networks in Philadelphia
        link: Learn more &rarr;
        alt: "The Philly Community Wireless logo - a vector graphic of the Liberty Bell 
             facing northeast, with radio waves emmitting from the top-right."
  es:
    languageName: Español
    contentDir: content/es
    menu:
      main:
        - name: Conéctate 
          identifier: get-connected
          weight: "1"
        - name: Conéctate
          url: "/getconnected"
          parent: get-connected
          weight: "1"
        - name: Voluntario
          url: "/volunteer"
          parent: get-connected
          weight: "2"
        # - name: Network Updates # should be deleted
        #   url: "/networkupdates"
        #   parent: get-connected
        #   weight: "3"

        - name: Donar
          url: https://phillycommunitywireless.allyrafundraising.com/
          params:
            external: true
          weight: "2"
      
        - name: Acerca 
          identifier: about-us
          weight: "3"
        - name: Acerca 
          url: "/about"
          parent: about-us
          weight: "1"
        - name: Novedades
          url: "/about/news"
          parent: about-us
        - name: Equipo
          url: "/about/people" 
          parent: about-us
          weight: "2"
        - name: Socios
          url: "/about/partners"
          parent: about-us
          weight: "3"
        - name: Cómo llegar aquí
          url: "/about/location"
          parent: about-us
          weight: "4"
        - name: Preguntas Frecuentes
          url: "/about/faq"
          parent: about-us
          weight: "5"

        - name: Navegacion
          url: "/networkmap"
          weight: "4"

        - name: Documentos
          url: https://docs.phillycommunitywireless.org/es/latest/
          params:
            external: true
          weight: "9"
    weight: "2"
    params:
      featured_text:
        header: "/images/WebLogo_Standard.svg"
        subtitle: Construyendo redes controladas por la comunidad en Filadelfia
        link: Aprende más &rarr;
        alt: "El logotipo de Philly Community Wireless: un gráfico vectorial de la 
              Campana de la Libertad orientada al noreste, con ondas de radio emitiéndose 
              desde la esquina superior derecha."
params:
  site_logo: "/images/WebLogo_Standard2.svg"
  site_logo_inverted: "/images/WebLogo_Inverted2.svg"
  attribution:
    name: Addie Barron
    link: https://addieis.online
  featured_image:
    src: "/images/Iglesias_AP_Equipment.jpg"
    alt:
      A photo of an antenna installed on a rooftop, pointing at a receiver tower
      in the distance.
    class: "opos-70p" 
  featured_text:
    header: "/images/WebLogo_Standard.svg"
  background_color_class: bg-near-white black-60
  body_classes: calibre black
  custom_css:
    - colors.css
    - custom.css
    - focus-indicators.css
    - fonts.css
markup:
  tableOfContents:
    startLevel: 0
  goldmark:
    renderer:
      unsafe: true
