---
baseURL: https://phillycommunitywireless.org
languageCode: en-us
defaultContentLanguage: en
title: Philly Community Wireless
author: Philly Community Wireless
theme: pcw-hugo-theme
enableRobotsTXT: true
languages:
  en:
    languageName: English
    contentDir: content/en
    menu:
      main:
        # Programs
        - name: Programs
          identifier: Programs
          weight: "1"
        - name: Get Connected
          url: "/getconnected"
          parent: Programs
          weight: "1"
        - name: Volunteer
          url: "/volunteer"
          parent: Programs
          weight: "2"        

        # Support
        - name: Support
          identifier: support
          weight: "2"
        - name: Donate
          url: "https://phillycommunitywireless.allyrafundraising.com/"
          params:
            external: true
          parent: support
          weight: "3"
        - name: Merch
          url: "/merch"
          parent: support
          weight: "2"
        - name: Support Us
          url: "/support"
          parent: support
          weight: "1"

        # About
        - name: About 
          identifier: about-us
          weight: "3"
        - name: About Us
          url: "/about"
          parent: about-us
          weight: "1"
        - name: People
          url: "/about/people"
          parent: about-us
          weight: "2"
        - name: Partners
          url: "/about/partners"
          parent: about-us
          weight: "3"
        - name: Funders
          url: "/about/funders"
          parent: about-us
          weight: "4"
        - name: In the News 
          url: "/about/news"
          parent: about-us
          weight: "5"
        - name: Resources
          url: "/resources"
          parent: about-us
          weight: "6"
        - name: FAQ
          url: "/about/faq"
          parent: about-us
          weight: "7"
     
          # Location
        - name: Location
          identifier: Location
          weight: "4"
        - name: Network Map
          url: "/networkmap"
          parent: Location
          weight: "1"
        - name: HQ Location
          url: "/hq"
          parent: Location
          weight: "2"
        - name: Air Monitors
          url: "/airmonitor"
          parent: Location
          weight: "3"

         # Docs
        - name: Docs 
          identifier: Docs
          weight: "5"
        - name: Docs
          url: "https://docs.phillycommunitywireless.org/en/latest/"
          params:
            external: true
          parent: Docs
          weight: "1"
        - name: Installations
          url: "https://docs.phillycommunitywireless.org/en/latest/installations/installations/"
          params:
            external: true
          parent: Docs
          weight: "2"
        - name: Troubleshooting
          url: "https://docs.phillycommunitywireless.org/en/latest/device-configuration/troubleshoot-devices/"
          params:
            external: true
          parent: Docs
          weight: "3"

        - name: Contact
          url: /contact
          identifier: Contact
          weight: "6"
          
    weight: "1"
    params:
      featured_text:
        header: "/images/WebLogo_Standard.svg"
        subtitle: Building community-controlled networks in Philadelphia
        link: Learn more &rarr;
        alt: "The Philly Community Wireless logo - a vector graphic of the Liberty Bell 
             facing northeast, with radio waves emmitting from the top-right."
  es:
    languageName: Español
    contentDir: content/es
    menu:
      main:

          # Programas
        - name: Programas
          identifier: Programas
          weight: "1"
        - name: Conéctate
          url: "/getconnected"
          parent: Programas
          weight: "1"
        - name: Ser voluntario
          url: "/volunteer"
          parent: Programas
          weight: "2"  

          # Apóyanos
        - name: Apóyanos
          identifier: Apóyanos
          weight: "2"
        - name: Donaciones
          url: "https://phillycommunitywireless.allyrafundraising.com/"
          params:
            external: true
          parent: Apóyanos
          weight: "3"
        - name: Artículos en venta
          url: "/merch"
          parent: Apóyanos
          weight: "2"
        - name: Cómo apoyarnos
          url: "/support"
          parent: Apóyanos
          weight: "1"

        - name: Acerca 
          identifier: about-us
          weight: "3"
        - name: Acerca PCW
          url: "/about"
          parent: about-us
          weight: "1"
        - name: Equipo
          url: "/about/people" 
          parent: about-us
          weight: "2"
        - name: Socios
          url: "/about/partners"
          parent: about-us
          weight: "3"
        - name: Patrocinadores
          url: "/about/funders"
          parent: about-us
          weight: "4"
        - name: Novedades
          url: "/about/news"
          parent: about-us
          weight: "5"
        - name: Recursos
          url: "/resources"
          parent: about-us
          weight: "6"
        - name: Preguntas Frecuentes
          url: "/about/faq"
          parent: about-us
          weight: "7"

        - name: Ubicación
          identifier: location
          weight: "4"
        - name: Mapa de red PCW
          url: "/networkmap"
          parent: location
          weight: "1"
        - name: Cómo llegar aquí
          url: "/hq"
          parent: location
          weight: "2"
        - name: Monitores de aire
          url: "/airmonitor"
          parent: location
          weight: "3"

        - name: Documentos 
          identifier: documentos
          weight: "5"
        - name: Instalacion
          url: https://docs.phillycommunitywireless.org/es/latest/Instalaci%C3%B3ndeantenas/
          params:
            external: true
          parent: documentos
          weight: "1"
        - name: Recursos
          url: https://docs.phillycommunitywireless.org/es/latest/recursos/
          params:
            external: true
          parent: documentos
          weight: "2"
        - name: Contact
          url: /contact
          identifier: Contact
          weight: "6"
    weight: "2"
    params:
      featured_text:
        header: "/images/WebLogo_Standard.svg"
        subtitle: Construyendo redes controladas por la comunidad en Filadelfia
        link: Aprende más &rarr;
        alt: "El logotipo de Philly Community Wireless: un gráfico vectorial de la 
              Campana de la Libertad orientada al noreste, con ondas de radio emitiéndose 
              desde la esquina superior derecha."
params:
  site_logo: "/images/WebLogo_Standard2.svg"
  site_logo_inverted: "/images/WebLogo_Inverted2.svg"
  attribution:
    name: Addie Barron, and mamy volunteers
    link: https://addieis.online
  featured_image:
    src: "/images/Iglesias_AP_Equipment.jpg"
    alt:
      A photo of an antenna installed on a rooftop, pointing at a receiver tower
      in the distance.
    class: "opos-70p" 
  featured_text:
    header: "/images/WebLogo_Standard.svg"
  background_color_class: black-60
  body_classes: calibre black
  custom_css:
    - colors.css
    - custom.css
    - focus-indicators.css
    - fonts.css
markup:
  tableOfContents:
    startLevel: 0
  goldmark:
    renderer:
      unsafe: true
