baseURL = "https://phillycommunitywireless.com/"
languageCode = "en-us"
title = "Philly Community Wireless Project"
theme = "pcwp-hugo"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableEmoji = true
publishDir = "docs"

[taxonomies]
  author = "authors"
  tag = "tags"
  order = "orders"

[permalinks]
  issues = "/:sections/:slug/"

[outputs]
  page = ["HTML"]
  home = ["HTML"]

[menu]

  [[menu.main]]
    name = "The Project"
    url = "project/"
    weight = 10

  [[menu.main]]
    name = "People"
    url = "people/"
    weight = 20

  [[menu.main]]
    name = "Resources"
    url = "resources/"
    weight = 30

[params]
  google_fonts = [
    ["Eczar"],
    ["Lato"],
    ["Arvo"],
    ["Cormorant"],
    ["Scope One"],
    ["Rufina"],
    ["Josefin Sans"],
  ]

  heading_font = "Ecxar"
  body_font = "Josefin Sans"

  dateform        = "January 2, 2006"
  dateformShort   = "January 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

[markup.goldmark.renderer]
  unsafe = true
